# -*- coding: utf-8 -*-
"""untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/akirahatsu/8738ffa77ee39ff3be57009d6d3e676d/untitled0.ipynb
"""

#derivative calulation fro fun and experement

x = range(1,10)

#function

def derivatve(x , h = 1e-6 ,operation = "x**2"):
  '''
  here operation means f(x) == function
  '''
  # determining f(x+▲x)

  delt_f = x+h

  #function simplifyng

  operation = operation.replace("+" ," + ").replace("-" , " - ").replace("^^" , "**")

  box = []

  for el in operation.split():
    if "**" in el:
      #for determine is it exponential or not
      if el[0].isalpha() and el[-1].isdigit():
        #this part quite complicated but funny if you underestand :)
        box.append(str(((eval(el , {"x":delt_f})-eval(el))/h)))

      elif  el[-1].isalpha() and el[0].isdigit():
        box.append(str((((eval(el))*(x**h)-eval(el))/h)))
    #i tried to use and or thing but cannot inplement is so laziness :)
    elif el == "-":
      box.append("-")
    elif el == "+":
      box.append("+")
    else:
      box.append(str(((eval(el, {"x":delt_f})-eval(el))/h)))
  #we compbine whole structure  and evaluate
  box = "".join(box)

  return eval(box)



#sample
derivatve(2 , operation="2**x-2x")